version: "3"
services:
  app:
    container_name: app_container
    build: ./docker/app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: yarn dev #開発環境が整ったら追加

  api:
    container_name: api_container
    build: ./docker/api
    command: npm run dev
    ports:
      - 3000:3000
    tty: true
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/app
    depends_on: 
      - db

  db:
    container_name: db_container
    build: ./docker/db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf # MySQLの設定をバインド
      - ./db/init_db:/docker-entrypoint-initdb.d # 初期データ投入用のsqlファイルをバインド
      - test_data:/var/lib/mysql # 永続化したデータをバインド
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} # コンテナの環境変数から各種設定を読み込み
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ="Asia/Tokyo"

volumes:
  test_data:
